チャンネル一覧を取得するAPI
givery-bootcamp/dena-2024-team2 pull request #18
Opened 2024-05-28 06:49 UTC by TakanoHori

## 概要
作成されているチャンネルの一覧を取得するAPI

### 動作確認
- `docker compose up` して `localhost:9000/channel` を curl したときに以下のような配列が取得できる
```
% curl localhost:9000/channel
[{"Id":1,"ServerId":1,"Name":"channel1","CreatedAt":"2024-05-28T10:24:24+09:00","UpdatedAt":"2024-05-28T10:24:24+09:00","DeletedAt":"0001-01-01T00:00:00Z"},{"Id":2,"ServerId":1,"Name":"channel2","CreatedAt":"2024-05-28T10:24:24+09:00","UpdatedAt":"2024-05-28T10:24:24+09:00","DeletedAt":"0001-01-01T00:00:00Z"}]
```

2024-05-28 06:53 UTC, TakanoHori commented on backend/internal/entities/channel.go
エンティティと repository.go の両方でこの構造体を宣言している理由をもう1回確認したい。

2024-05-28 06:54 UTC, TakanoHori commented on backend/internal/entities/channel.go
> +}
エンティティと repository.go の両方でこの構造体を宣言している理由をもう1回確認したい。

2024-05-28 07:25 UTC, TakanoHori commented
関係する Issue https://github.com/givery-bootcamp/dena-2024-team2/issues/3

2024-05-28 07:28 UTC, syougo1209 commented on backend/internal/repositories/get_channels_repository.go
> +		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
自分もさっき知ったんだけど、gorm.ErrRecordNotFoundは`r.Conn.Find`使うと使うと返ってこないみたい。(First, Take, Lastとかを使う必要があるらしい）
https://gorm.io/docs/query.html#Retrieving-a-single-object

チャンネル一覧を取得するときにレコードが一件もないのはあり得そうだから、Findのままで良さそうだけど、このエラーの分岐の部分は消してしまって良さそう

2024-05-28 07:53 UTC, TakanoHori commented on backend/internal/repositories/get_channels_repository.go
> +		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
試しに、`channels` テーブルを empty にして検証してみましたが、`result.Error` は `nil` だったので、if 文以下は消しておきます。

2024-05-28 07:57 UTC, TakanoHori commented on backend/internal/repositories/get_channels_repository.go
> +		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
修正しました！

2024-05-28 08:54 UTC, TakanoHori commented
@syougo1209 もらったコメントの部分と lint の適用で変わったところを修正しています

2024-06-17 06:35 UTC, syougo1209 commented on backend/internal/entities/channel.go
> +}
二つ宣言している理由はDBとかの変更が依存しないように設計するためです。entitiesにはdbとは関係ないチャンネル固有のメソッド見たいなやつが映える予定で、entitiesに定義したオブジェクトはいろんなとこで使いまわしたいです。そのentitesがrepositoryのようなDBからデータを持ってくる部分に依存していると、例えばdbとかのスキーマを変更したときに影響範囲がデカくなってしまうので、わざわざ二つ作っている感じです。以下の記事とか参考にしていたりします！
https://tech.mirrativ.stream/entry/2020/11/30/142354

ただ、ここら辺の分けるか分けないかは好みなところはあると思います！

2024-06-17 06:35 UTC, syougo1209 commented on backend/internal/repositories/get_channels_repository.go
> +}
最後に空行入れたほうがいいかも
https://qiita.com/hamacccccchan/items/11c17c7412a5aeb2ad74

2024-06-17 06:36 UTC, syougo1209 commented on backend/internal/entities/channel.go
> +}
ここも改行入れた方がいいかも

2024-06-17 06:37 UTC, syougo1209 requested changes
改行だけコメントしたので、確認お願いします！

2024-06-17 07:32 UTC, TakanoHori commented on backend/internal/entities/channel.go
> +}
ありがとうございます！参考にさせていただきますmm

2024-06-17 07:35 UTC, syougo1209 submitted a review, later dismissed

2024-06-17 07:53 UTC, syougo1209 approved these changes

2024-06-17 07:53 UTC, merged