add deploy setting
givery-bootcamp/dena-2024-team2 pull request #23
Opened 2024-06-11 07:34 UTC by syougo1209

2024-06-11 08:41 UTC, himantyu-yuma approved these changes
構築あざます！

2024-06-11 08:42 UTC, himantyu-yuma requested changes

2024-06-11 08:42 UTC, himantyu-yuma commented on .github/workflows/deploy.yml
> +      - '**'
あ！ここmainに直しておいてもらえると 🙏

2024-06-11 08:54 UTC, syougo1209 commented on .github/workflows/deploy.yml
> +      - '**'
branch設定している箇所全部mainに変更しました！
d15e17ff54666479db431c5d6705df9c946dcc1c

2024-06-11 08:54 UTC, syougo1209 commented on .github/workflows/deploy.yml
> +      - '**'
@himantyu-yuma

2024-06-17 05:32 UTC, himantyu-yuma approved these changes

2024-06-17 05:33 UTC, merged