新規投稿の登録API
givery-bootcamp/dena-2024-team2 pull request #29
Opened 2024-06-17 07:29 UTC by nihei-shunsuke

### 概要
新しい投稿をDBに登録するAPI

<img width="843" alt="スクリーンショット 2024-06-17 16 29 20" src="https://github.com/givery-bootcamp/dena-2024-team2/assets/69235807/cfc4e527-996a-43af-8cca-e390de7f2f3a">

2024-06-17 07:33 UTC, himantyu-yuma reviewed
一箇所コメントしました！

2024-06-17 07:33 UTC, himantyu-yuma commented on backend/internal/controllers/create_post_controller.go
> +	fmt.Println("確認", post)
（純粋な質問）こういうdebug用の出力って消さない？

2024-06-17 07:42 UTC, nihei-shunsuke commented on backend/internal/controllers/create_post_controller.go
> +	fmt.Println("確認", post)
あーーーシンプル怠惰
消します！！

2024-06-17 08:19 UTC, toliner requested changes

2024-06-17 08:19 UTC, toliner commented on backend/internal/entities/post.go
> -type Posts []Post
ここのPostsを消したのに、それを参照する箇所は消してないからget_post_repository等でエラーが出てる。
Postsは消さないで良かったかも。

2024-06-18 04:42 UTC, syougo1209 commented on mysql/sql/create.sql
> +  content       TEXT         NOT NULL,
テーブルのカラム名適当につけてたかも🙏
修正ありがとう！

2024-06-18 04:44 UTC, syougo1209 commented on backend/internal/repositories/create_post_repository.go
> +		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
gormのCreateメソッドでErrRecordNotFoundエラー返ってくるのかな？
返ってこなそうだったら、消しても良さそう

2024-06-18 04:50 UTC, syougo1209 commented on backend/internal/entities/post.go
> +	DeletedAt *time.Time `json:"deleted_at"`
jsonとのマッピングのところはcontrollerでやっても良さそう。
ここのentitiesは自分のイメージだとpostに関するロジックを定義したいところだと思っていて、特定のレスポンスの形に依存すると、使いづらくなってしまいそうで、 jsonのレスポンスも必ずしもentitiesのものと一致するとは限らないから、controllerとかでjsonのレスポンスとマッピングした構造体を作ってもいいのではと思いました！

2024-06-18 04:54 UTC, syougo1209 commented on backend/internal/entities/post.go
> +	DeletedAt *time.Time `json:"deleted_at"`
上ではcontrollerとentity , databaseを分けた方がいいと言っているけど、時間ない中での開発だから、ここで定義してしまっても良いとおもう！dbとスキーマ一致してればデータ取得OR作成するときも構造体詰め替える必要なくて楽だし

2024-06-18 04:59 UTC, syougo1209 commented on backend/internal/middleware/router.go
> +	app.POST("/create_post", controllers.CreatePost)
細かいけどpathの名前は名詞の方が自分は好きです。HTTPメソッドでPOSTっていう動詞に対して、リソースを操作するみたいなイメージなので、名刺の方が好きです。
https://qiita.com/mserizawa/items/b833e407d89abd21ee72

あと、特定のchannelsに対して、postsを作るからpathが"/channels/:id/posts"でも良い気がする。

2024-06-18 05:00 UTC, syougo1209 requested changes
何箇所かコメントしました！

2024-06-18 05:03 UTC, toliner requested changes

2024-06-18 05:40 UTC, nihei-shunsuke commented on backend/internal/middleware/router.go
> +	app.POST("/create_post", controllers.CreatePost)
done

2024-06-18 05:43 UTC, nihei-shunsuke commented on backend/internal/repositories/get_post_repository.go
> +	if err := r.Conn.Table("posts").Select("posts.id, posts.channel_id, posts.user_id, posts.content, posts.created_at, posts.updated_at").Joins("join users on posts.user_id = users.id").Where("channel_
done

2024-06-18 05:44 UTC, nihei-shunsuke commented on backend/internal/repositories/create_post_repository.go
> +		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
done

2024-06-18 08:08 UTC, syougo1209 commented on backend/internal/controllers/create_post_controller.go
> +	}
前のPRでコメントできていなかったけど、ginだとpostされたjsonを下みたいな感じでbindしてるから、こっち使っても良さそう
https://go.dev/doc/tutorial/web-service-gin
```
var newAlbum album

    // Call BindJSON to bind the received JSON to
    // newAlbum.
    if err := c.BindJSON(&newAlbum); err != nil {
        return
    }
```

2024-06-18 08:35 UTC, nihei-shunsuke commented on backend/internal/controllers/create_post_controller.go
> +	}
@syougo1209 
修正完了しましたー！

2024-06-24 05:35 UTC, syougo1209 commented on backend/internal/controllers/create_post_controller.go
> +	result, err := usecase.Execute(post)
result, err := usecase.Execute(body, channelid, userid)

2024-06-24 08:27 UTC, syougo1209 commented on backend/internal/controllers/create_post_controller.go
> +
requestparams {
body
channelID 
}

2024-06-25 04:58 UTC, syougo1209 submitted a review, later dismissed
LGTM

2024-06-25 05:51 UTC, syougo1209 commented
@nihei-shunsuke 
ここだけ直したので、見てくれると助かる！
a8aa40db513c790f6c9f7cba8337dd0545b3ac0d
a5052038ad1a6e806b8324bc0cbda14275d9fb2a

2024-06-25 05:52 UTC, syougo1209 approved these changes
lgtm

2024-06-25 07:18 UTC, TakanoHori approved these changes
大丈夫だと思いますー！

2024-06-25 07:34 UTC, merged